set SLACK_CLIENT_ID=
set SLACK_CLIENT_SECRET=
set SLACK_SIGNING_SECRET=
set SLACK_APP_TOKEN=
set SLACK_BOT_TOKEN=

set DB_NAME=
set DB_USERNAME=
set DB_PASSWORD=

set AWS_ACCESS_KEY_ID=
set AWS_SECRET_ACCESS_KEY=
set AWS_S3_BUCKET_NAME=
set AWS_SECRET_NAME=
set AWS_DEFAULT_REGION=

set POST_QUESTION_URL=
set SEARCH_QUESTION_URL=